# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      # 生成静态文件
    - run: npm run docs:build
          cd docs/.vuepress/dist
          echo 'www.sumarin.cn' > CNAME
          git init
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:Sumarina/Monday.git master:gh-pages
          cd -
