# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
          #!/usr/bin/env sh
          set -e
          npm ci
          npm run docs:build
          cd docs/.vuepress/dist
          echo 'www.sumarin.cn' > CNAME
          git init
          git add -A
          echo 'git config'
          git config --global user.email "marinzoo@hotmail.com"
          git config --global user.name "sumarina"
          echo 'git commit'
          git commit -m 'deploy'
          echo 'git remote add'
          git remote add origin git@github.com:Sumarina/Monday.git
          echo 'git set-url'
          git remote set-url origin https://${GITHUB_ACTOR}:${repo-token}@github.com/${GITHUB_REPOSITORY}
          git push -f git@github.com:Sumarina/Monday.git master:gh-pages
          cd -
      
