# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        super_secret: ${{ secrets.monday }} 
      env: 
        super_secret: ${{ secrets.monday }}
    - run: npm ci
    - run: npm run docs:build
    - run: cd docs/.vuepress/dist
    - run: echo 'www.sumarin.cn' > CNAME
    - run: git init
    - run: git add -A
    - run: git config --global user.email "marinzoo@hotmail.com"
    - run: git config --global user.name "sumarina"
    - run: git commit -m 'deploy'
    - run: git push -f git@github.com:Sumarina/Monday.git master:gh-pages
    - run: cd -
